apiVersion: v1
kind: Service
metadata:
  name: ecsdemo-nodejs
  namespace: clb-test
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  
spec:
  selector:
    app: ecsdemo-nodejs
#  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000

